{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "2fauth.fullname" . }}
  namespace: {{ include "2fauth.namespace" . }}
  labels:
    {{- include "2fauth.labels" . | nindent 4 }}
  {{- with (include "2fauth.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "2fauth.instanceSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8000
          protocol: TCP
      {{- with .Values.networkPolicy.allowedIngress }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  egress:
    {{- /* DNS is always required, whatever else is allowed. */}}
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if .Values.networkPolicy.allowAllEgress }}
    - {}
    {{- end }}
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
