{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "2fauth.fullname" . }}
  namespace: {{ include "2fauth.namespace" . }}
  labels:
    {{- include "2fauth.labels" . | nindent 4 }}
  {{- with (include "2fauth.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "2fauth.selectorLabels" . | nindent 6 }}
{{- end }}
